sudo apt install git
sudo apt install python3-dev python3-pip
sudo apt install ruby-full
sudo apt install virtualbox
sudo apt install build-essential
sudo apt install libssl-dev
sudo apt install libncurses5-dev
sudo apt install unzip
sudo apt install gawk
sudo apt install zlib1g-dev
sudo apt install gcc-6
sudo apt install tree
sudo apt install meld
sudo apt install openssh-server
sudo apt install docker.io
sudo apt install curl
sudo apt install openssl
sudo apt install jq
sudo apt install cpanminus
sudo apt install astyle
sudo apt install exuberant-ctags
sudo apt install tmux
sudo apt install xclip
sudo apt install tldr
sudo apt install silversearcher-ag
sudo apt install autojump
sudo apt install htop
sudo gem install terjira
sudo pip3 install thefuck
